version: '3.7'

services:
  angular:
    build: ./Angular
    volumes:
      - ./Angular:/usr/src/app
    ports:
      - 8080:80
    depends_on:
      - flask

  flask:
    build: ./Flask
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./Flask:/app/flask
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
     - POSTGRES_DB=source_meridian
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

volumes:
  postgres_data: